app_abbreviation_api:
    type: rest
    prefix: /admin/api
    resource: Manuxi\SuluAbbreviationsBundle\Controller\Admin\AbbreviationsController
    name_prefix: sulu_abbreviations.
    options:
        expose: true

